import React, { useState, useEffect } from 'react';
import { X, Mic } from 'lucide-react';
import axios from 'axios';

import API_BASE_URL from '../config';

const PodcastModal = ({ onClose }) => {
    const [audioUrl, setAudioUrl] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchPodcast = async () => {
            try {
                const res = await axios.get(`${API_BASE_URL}/api/podcast/today`, { responseType: 'blob' });
                const url = URL.createObjectURL(res.data);
                setAudioUrl(url);
            } catch (err) {
                setError(err.message || "Failed to generate briefing");
            } finally {
                setLoading(false);
            }
        };
        fetchPodcast();
    }, []);

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center animate-fade-in">
            <div className="panel-aura rounded-md w-full max-w-md m-4 overflow-hidden relative">
                <button
                    onClick={onClose}
                    className="absolute top-4 right-4 text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition-colors"
                >
                    <X size={20} />
                </button>

                <div className="p-6">
                    <h2 className="text-lg font-bold uppercase tracking-tight text-[var(--color-text-primary)] flex items-center mb-6">
                        <Mic className="mr-2 text-[var(--color-accent)]" size={20} /> Daily Briefing
                    </h2>

                    <div className="bg-[var(--color-bg-tertiary)] rounded-sm p-4 min-h-[150px] flex items-center justify-center border border-[var(--color-border)]">
                        {loading ? (
                            <div className="flex flex-col items-center">
                                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[var(--color-accent)] mb-3"></div>
                                <p className="text-[var(--color-text-primary)] text-sm font-medium">Generating briefing...</p>
                                <p className="text-[10px] text-[var(--color-text-secondary)] mt-1 uppercase tracking-wide">Synthesizing recent events</p>
                            </div>
                        ) : error ? (
                            <p className="text-[var(--color-accent)] text-center text-sm">{error}</p>
                        ) : (
                            <div className="w-full">
                                <audio controls autoPlay src={audioUrl} className="w-full h-10" />
                                <p className="text-center text-[10px] text-[var(--color-text-secondary)] uppercase tracking-wide mt-3">Audio Generated by AI</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PodcastModal;
